export const languagesList: string[] = [
  // African and Global
  'Afrikaans',
  'Akan',
  'Amharic',
  'Arabic',
  'Armenian',
  'Azerbaijani',
  'Basque',
  'Belarusian',
  'Bosnian',
  'Bulgarian',
  'Catalan',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English (United Kingdom)',
  'English (United States)',
  'Estonian',
  'Filipino',
  'Finnish',
  'French',
  'Galician',
  'Georgian',
  'German',
  'Greek',
  'Haitian Creole',
  'Hausa',
  'Hebrew',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Kazakh',
  'Khmer',
  'Kinyarwanda',
  'Korean',
  'Kurdish (Central)',
  'Latvian',
  'Lithuanian',
  'Luxembourgish',
  'Macedonian',
  'Malay',
  'Maltese',
  'Māori',
  'Mongolian',
  'Norwegian (Bokmål)',
  'Norwegian (Nynorsk)',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese (Brazil)',
  'Portuguese (Portugal)',
  'Quechua',
  'Romanian',
  'Russian',
  'Serbian',
  'Slovak',
  'Slovenian',
  'Somali',
  'Spanish',
  'Swahili',
  'Swedish',
  'Tagalog',
  'Thai',
  'Turkish',
  'Turkmen',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Vietnamese',
  'Welsh',
  'Xhosa',
  'Zulu',

  // 🇮🇳 Indian Languages (in English)
  'Assamese',
  'Bengali',
  'Bodo',
  'Dogri',
  'Gujarati',
  'Hindi',
  'Kannada',
  'Kashmiri',
  'Konkani',
  'Maithili',
  'Malayalam',
  'Manipuri',
  'Marathi',
  'Nepali',
  'Odia',
  'Punjabi',
  'Sanskrit',
  'Santali',
  'Sindhi',
  'Tamil',
  'Telugu',
  'Urdu (India)',
  'Tulu',
  'Khasi',
  'Mizo',
  'Garo',
  'Tripuri',
  'Nicobarese',
  'Bhili',
  'Kurukh',
  'Gondi',
  'Braj',
  'Rajasthani',
  'Chhattisgarhi',
  'Garhwali',
  'Kumaoni',
  'Magahi',
  'Awadhi',
  'Angika',
  'Bhojpuri'
];
